"""
Canonical seed data for hackathon demo.
12 recurring streams covering varied scenarios per DATA_MODEL.md.
"""
from datetime import date

DEMO_ORG_ID = "org_demo"
DEMO_USER_ID = "Acme Corp"

RECURRING_STREAMS = [
    {
        "id": "stream_001",
        "org_id": DEMO_ORG_ID,
        "merchant": "Notion",
        "raw_merchant": "NOTION.SO",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 320.00,
        "seat_count": 16,
        "usage_signal": "none",
        "confidence": 0.91,
        "is_protected": False,
        "notes": "16 seats licensed. 0 logins in 90 days. Overlap with Confluence.",
        "first_seen": "2023-01-15",
        "last_seen": "2026-03-01",
        "occurrence_count": 38,
        "source": "bank",
    },
    {
        "id": "stream_002",
        "org_id": DEMO_ORG_ID,
        "merchant": "Figma",
        "raw_merchant": "FIGMA INC",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 180.00,
        "seat_count": 10,
        "usage_signal": "low",
        "confidence": 0.85,
        "is_protected": False,
        "notes": "3 of 10 seats active in last 30 days.",
        "first_seen": "2023-03-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 36,
        "source": "bank",
    },
    {
        "id": "stream_003",
        "org_id": DEMO_ORG_ID,
        "merchant": "Zoom",
        "raw_merchant": "ZOOM.US",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 240.00,
        "seat_count": 12,
        "usage_signal": "low",
        "confidence": 0.72,
        "is_protected": False,
        "notes": "Overlap with Microsoft Teams (active). Potential duplicate.",
        "first_seen": "2022-11-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 40,
        "source": "bank",
    },
    {
        "id": "stream_004",
        "org_id": DEMO_ORG_ID,
        "merchant": "Adobe Creative Cloud",
        "raw_merchant": "ADOBE SYSTEMS",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 600.00,
        "seat_count": 8,
        "usage_signal": "low",
        "confidence": 0.88,
        "is_protected": False,
        "notes": "2 of 8 seats active. Consider downgrade to individual plan.",
        "first_seen": "2022-06-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 45,
        "source": "bank",
    },
    {
        "id": "stream_005",
        "org_id": DEMO_ORG_ID,
        "merchant": "AWS",
        "raw_merchant": "AMAZON WEB SERVICES",
        "category": "cloud",
        "cadence": "monthly",
        "amount_usd": 890.00,
        "seat_count": None,
        "usage_signal": "low",
        "confidence": 0.65,
        "is_protected": False,
        "notes": "Dev account overprovisioned. Rightsizing recommended.",
        "first_seen": "2021-09-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 54,
        "source": "bank",
    },
    {
        "id": "stream_006",
        "org_id": DEMO_ORG_ID,
        "merchant": "Slack",
        "raw_merchant": "SLACK TECHNOLOGIES",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 1200.00,
        "seat_count": 60,
        "usage_signal": "active",
        "confidence": 0.10,
        "is_protected": True,
        "notes": "Core communication tool. Active usage across all teams. Do not touch.",
        "first_seen": "2021-01-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 62,
        "source": "slack",
    },
    {
        "id": "stream_007",
        "org_id": DEMO_ORG_ID,
        "merchant": "Asana",
        "raw_merchant": "ASANA INC",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 280.00,
        "seat_count": 14,
        "usage_signal": "low",
        "confidence": 0.78,
        "is_protected": False,
        "notes": "Overlap with Jira (active). Team split between both tools.",
        "first_seen": "2022-08-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 43,
        "source": "bank",
    },
    {
        "id": "stream_008",
        "org_id": DEMO_ORG_ID,
        "merchant": "Dropbox",
        "raw_merchant": "DROPBOX INC",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 150.00,
        "seat_count": 10,
        "usage_signal": "low",
        "confidence": 0.80,
        "is_protected": False,
        "notes": "Overlap with Google Drive (active). Most files migrated.",
        "first_seen": "2022-04-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 47,
        "source": "gmail",
    },
    {
        "id": "stream_009",
        "org_id": DEMO_ORG_ID,
        "merchant": "Webflow",
        "raw_merchant": "WEBFLOW INC",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 75.00,
        "seat_count": 3,
        "usage_signal": "none",
        "confidence": 0.93,
        "is_protected": False,
        "notes": "Last login 120 days ago. Site not updated in 4 months.",
        "first_seen": "2023-05-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 34,
        "source": "bank",
    },
    {
        "id": "stream_010",
        "org_id": DEMO_ORG_ID,
        "merchant": "LinkedIn Sales Navigator",
        "raw_merchant": "LINKEDIN SALES NAV",
        "category": "saas",
        "cadence": "annual",
        "amount_usd": 1600.00,
        "seat_count": 5,
        "usage_signal": "low",
        "confidence": 0.70,
        "is_protected": False,
        "notes": "1 of 5 seats actively used in last 60 days.",
        "first_seen": "2023-02-01",
        "last_seen": "2026-02-01",
        "occurrence_count": 3,
        "source": "bank",
    },
    {
        "id": "stream_011",
        "org_id": DEMO_ORG_ID,
        "merchant": "Heroku",
        "raw_merchant": "HEROKU INC",
        "category": "cloud",
        "cadence": "monthly",
        "amount_usd": 340.00,
        "seat_count": None,
        "usage_signal": "low",
        "confidence": 0.60,
        "is_protected": False,
        "notes": "Staging environment with low traffic. Could be shut down or migrated to Render.",
        "first_seen": "2022-03-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 48,
        "source": "bank",
    },
    {
        "id": "stream_012",
        "org_id": DEMO_ORG_ID,
        "merchant": "Loom",
        "raw_merchant": "LOOM INC",
        "category": "saas",
        "cadence": "monthly",
        "amount_usd": 120.00,
        "seat_count": 8,
        "usage_signal": "low",
        "confidence": 0.82,
        "is_protected": False,
        "notes": "Overlap with Zoom (already flagged). Low usage since Zoom clips feature launched.",
        "first_seen": "2023-06-01",
        "last_seen": "2026-03-01",
        "occurrence_count": 33,
        "source": "slack",
    },
]
