from schemas import RecurringStream, Cadence, UsageSignal

STUB_STREAMS = [
    RecurringStream(
        id="stream_001",
        merchant="Notion",
        raw_merchant="NOTION.SO",
        category="saas",
        cadence=Cadence.monthly,
        amount_usd=320.00,
        seat_count=16,
        usage_signal=UsageSignal.none,
        confidence=0.95,
        is_protected=False,
        notes="0 logins in 90 days. Confluence active for same use case.",
        first_seen="2023-01-15",
        last_seen="2024-03-01",
        occurrence_count=14,
    ),
    RecurringStream(
        id="stream_002",
        merchant="Zoom",
        raw_merchant="ZOOM.US",
        category="saas",
        cadence=Cadence.monthly,
        amount_usd=180.00,
        seat_count=20,
        usage_signal=UsageSignal.low,
        confidence=0.88,
        is_protected=False,
        notes="Google Meet already active across org.",
        first_seen="2022-06-01",
        last_seen="2024-03-01",
        occurrence_count=21,
    ),
    RecurringStream(
        id="stream_003",
        merchant="Slack",
        raw_merchant="SLACK TECHNOLOGIES",
        category="saas",
        cadence=Cadence.monthly,
        amount_usd=850.00,
        seat_count=50,
        usage_signal=UsageSignal.active,
        confidence=0.99,
        is_protected=True,
        notes=None,
        first_seen="2021-03-01",
        last_seen="2024-03-28",
        occurrence_count=36,
    ),
    RecurringStream(
        id="stream_004",
        merchant="Figma",
        raw_merchant="FIGMA INC",
        category="saas",
        cadence=Cadence.annual,
        amount_usd=450.00,
        seat_count=5,
        usage_signal=UsageSignal.low,
        confidence=0.80,
        is_protected=False,
        notes="Only 1 of 5 seats active in last 60 days.",
        first_seen="2023-04-01",
        last_seen="2024-03-01",
        occurrence_count=2,
    ),
    RecurringStream(
        id="stream_005",
        merchant="AWS",
        raw_merchant="AMAZON WEB SERVICES",
        category="cloud",
        cadence=Cadence.monthly,
        amount_usd=2200.00,
        seat_count=None,
        usage_signal=UsageSignal.active,
        confidence=0.99,
        is_protected=True,
        notes=None,
        first_seen="2020-01-01",
        last_seen="2024-03-28",
        occurrence_count=51,
    ),
]
